export { default as Home } from './Home/NewHome'
export { ProfilePhotos, ProfilePosts, ProfileAbout } from './Profile/index'
export { default as Polling } from './Polling'
export { default as SignIn } from './Signin'
export { default as SignUp } from './Signup'
export { default as Settings } from './Settings/Settings'
export { default as Resources } from './Acad_New/Acads'
export { default as ChatApp } from './Chats (IMP)/ChatApp'
export { default as Friends } from './Friends/Friends'
export { default as Events } from './Events/Events'
export { default as Prof } from './Profile_New/Prof'
export { default as Parts } from './Participants/Parts'
export { default as Clubs } from './Clubs/Clubs'
export { default as Clubdesc } from './Clubs/Clubdesc'
