export { default as Home } from './Home/Home'
export { ProfilePhotos, ProfilePosts, ProfileAbout } from './Profile/index'
export { default as Polling } from './Polling'
export { default as SignIn } from './Signin'
export { default as SignUp } from './Signup'
export { default as Settings } from './Settings/Settings'
